// <auto-generated />
using System;
using HorarioEducativoWeb.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HorarioEducativoWeb.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260222221127_ActualizacionConfiguracionCentro")]
    partial class ActualizacionConfiguracionCentro
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Asignatura", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HorasSemanales")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Asignaturas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HorasSemanales = 4,
                            Nombre = "Álgebra Lineal"
                        },
                        new
                        {
                            Id = 2,
                            HorasSemanales = 6,
                            Nombre = "Desarrollo Web con .NET"
                        });
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Aula", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Codigo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Aulas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Codigo = "Lab-101"
                        },
                        new
                        {
                            Id = 2,
                            Codigo = "Aula-202"
                        });
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.CentroEducativo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RNC")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("InformacionCentro");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Direccion = "Av. Principal #123, Ciudad Educativa",
                            Nombre = "Centro Educativo Central",
                            RNC = "101-00000-1"
                        });
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Docente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Especialidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Docentes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Especialidad = "Matemáticas",
                            Nombre = "Juan Pérez"
                        },
                        new
                        {
                            Id = 2,
                            Especialidad = "Programación",
                            Nombre = "María García"
                        });
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Grupo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Modalidad")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Grupos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Modalidad = "Técnico en Informática",
                            Nombre = "4to de Media"
                        });
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Horario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AsignaturaId")
                        .HasColumnType("int");

                    b.Property<int>("AulaId")
                        .HasColumnType("int");

                    b.Property<string>("DiaSemana")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DocenteId")
                        .HasColumnType("int");

                    b.Property<int?>("DocenteId1")
                        .HasColumnType("int");

                    b.Property<int>("GrupoId")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("time");

                    b.HasKey("Id");

                    b.HasIndex("AsignaturaId");

                    b.HasIndex("AulaId");

                    b.HasIndex("DocenteId");

                    b.HasIndex("DocenteId1");

                    b.HasIndex("GrupoId");

                    b.ToTable("Horarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AsignaturaId = 1,
                            AulaId = 1,
                            DiaSemana = "Lunes",
                            DocenteId = 1,
                            GrupoId = 1,
                            HoraFin = new TimeSpan(0, 10, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 8, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Horario", b =>
                {
                    b.HasOne("HorarioEducativoWeb.Shared.Models.Asignatura", "Asignatura")
                        .WithMany("Horarios")
                        .HasForeignKey("AsignaturaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorarioEducativoWeb.Shared.Models.Aula", "Aula")
                        .WithMany("Horarios")
                        .HasForeignKey("AulaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HorarioEducativoWeb.Shared.Models.Docente", "Docente")
                        .WithMany()
                        .HasForeignKey("DocenteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HorarioEducativoWeb.Shared.Models.Docente", null)
                        .WithMany("Horarios")
                        .HasForeignKey("DocenteId1");

                    b.HasOne("HorarioEducativoWeb.Shared.Models.Grupo", "Grupo")
                        .WithMany("Horarios")
                        .HasForeignKey("GrupoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Asignatura");

                    b.Navigation("Aula");

                    b.Navigation("Docente");

                    b.Navigation("Grupo");
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Asignatura", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Aula", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Docente", b =>
                {
                    b.Navigation("Horarios");
                });

            modelBuilder.Entity("HorarioEducativoWeb.Shared.Models.Grupo", b =>
                {
                    b.Navigation("Horarios");
                });
#pragma warning restore 612, 618
        }
    }
}
